---
name: Build and Test on macOS
on:
  push:
    branches:
      - main

  workflow_dispatch:
    inputs:
      run_file:
        description: 'Job to be run'
        required: true
        default: 'test.py'

      
jobs:
  test:
    runs-on: macos-latest
    steps:
      - run: echo Hello github-actions
