---
name: Try Github Actions
on:
  push:
    branches:
      - main
    paths:
      - '**.py'

  workflow_dispatch:
    # inputs:
    #   run_file:
    #     description: 'Job to be run'
    #     required: true
    #     default: 'test.py'

    pull_request:
      type:
        - opened
        - labeled
        - synchronize
        - closed

      
jobs:
  test:
    runs-on: macos-latest
    steps:
      - run: echo Hello github-actions
