---
name: Try Github Actions
on:
  push:
    branches:
      - main
    paths:
      - '**.py'
  workflow_dispatch:
    
    pull_request:
      type: [opened, reopened, synchronize, closed, reopened]
      
jobs:
  test:
    runs-on: macos-latest
    steps:
      - run: echo Hello github-actions
      - if: ${{github.event_name == 'pull_request'}}
        uses: actions/checkout@v2
        with:
          mode: exactly

